import type { Metadata, Viewport } from "next";
import { Fraunces, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans", display: "swap" });
const fraunces = Fraunces({ subsets: ["latin"], variable: "--font-serif", display: "swap", weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "Beauty Inventory — Personal Skincare Inventory",
  description: "記錄您的保養品收藏，掌握截止日期，不再遺忘心愛的好物。",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Beauty Inventory",
  },
  icons: {
    icon: [
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

// Light mode only — Dark Mode was removed in Phase 4B.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#FAF8F4",
  viewportFit: "cover",
};

// iOS still needs an exact-pixel splash image per device (Safari doesn't
// synthesize one from the manifest the way Android does) — matched by
// CSS width/height + device-pixel-ratio media queries. Portrait only:
// manifest.json already locks orientation to "portrait-primary". Covers
// iPhone SE through the iPhone 16 generation, plus one common iPad size;
// generated by scripts/generate-pwa-assets.py.
const APPLE_SPLASH_SCREENS = [
  { width: 375, height: 667, dpr: 2, file: "iphone-se-8-750x1334.png" },
  { width: 390, height: 844, dpr: 3, file: "iphone-12-14-1170x2532.png" },
  { width: 393, height: 852, dpr: 3, file: "iphone-14pro-16-1179x2556.png" },
  { width: 402, height: 874, dpr: 3, file: "iphone-16pro-1206x2622.png" },
  { width: 428, height: 926, dpr: 3, file: "iphone-12-14-plusmax-1284x2778.png" },
  { width: 430, height: 932, dpr: 3, file: "iphone-14-16-plusmax-1290x2796.png" },
  { width: 440, height: 956, dpr: 3, file: "iphone-16promax-1320x2868.png" },
  { width: 834, height: 1194, dpr: 2, file: "ipad-11-1668x2388.png" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-Hant">
      <head>
        {/* Product-title serif stack is "Songti SC" / "Apple LiSong" (macOS/iOS
            system fonts) first, so this is only a fallback for other platforms —
            loaded as a plain stylesheet link rather than next/font, since its
            subset name isn't something we can safely verify without a live
            network fetch of Google's font metadata. */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font -- this rule targets the old Pages Router's _document.js; a <link> in the App Router root layout's <head> is the correct, supported place for this. */}
        <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@400;500&display=swap" rel="stylesheet" />
        {APPLE_SPLASH_SCREENS.map(({ width, height, dpr, file }) => (
          <link
            key={file}
            rel="apple-touch-startup-image"
            href={`/splash/${file}`}
            media={`(device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${dpr})`}
          />
        ))}
      </head>
      <body className={`${inter.variable} ${fraunces.variable} font-sans`}>{children}</body>
    </html>
  );
}
